#!/bin/bash
HOST="$ftp_domain"
USER="$ftp_user"
PASSWORD="$ftp_user_pass"

echo $HOST

DEST_DIR="/domains/pedromadureira.xyz/public_html"
SOURCE_DIR="~/Projects/pedromadureira.xyz/public"

lftp -u $ftp_user,$ftp_user_pass $ftp_domain << EOF
set ssl:verify-certificate false
set ftp:ssl-allow no
lcd $SOURCE_DIR
cd $DEST_DIR
mirror -R $SOURCE_DIR $DEST_DIR
bye
EOF
