#!/bin/bash

# echo "Creating backup on Documents/z.backup"
# zip -r /home/ph/Documents/z.backup/sync_vault.zip /home/ph/Documents/sync_vault
# zip -r /home/ph/Documents/z.backup/sync_vault_$(date +%Y%m%d_%H%M%S).zip /home/ph/Documents/sync_vault

# echo "You are about to LOAD changes FROM Google Drive"
# read -p "Type 'y' to confirm: " confirmation
# if [ "$confirmation" = "y" ]; then
    # rclone sync sync-vault:/sync_vault /home/ph/Documents/sync_vault --progress --stats-one-line -v --create-empty-src-dirs --fast-list --transfers=8 --checkers=16
# else
    # echo "Operation cancelled"
# fi
