#!/bin/bash

echo "Creating backup on Documents/z.backup"
zip -r /home/ph/Documents/z.backup/sync_vault.zip /home/ph/Documents/sync_vault
# zip -r /home/ph/Documents/z.backup/sync_vault_$(date +%Y%m%d_%H%M%S).zip /home/ph/Documents/sync_vault

echo "What do you want to do?"
echo "1. Load changes from Google Drive"
echo "2. Send changes to Google Drive"
read -p "Enter your choice (1 or 2): " choice

case $choice in
    1)
        echo "You are about to LOAD changes FROM Google Drive"
        read -p "Type 'yes' to confirm: " confirmation
        if [ "$confirmation" = "yes" ]; then
            rclone sync sync-vault:/sync_vault /home/ph/Documents/sync_vault --progress --stats-one-line -v --create-empty-src-dirs
        else
            echo "Operation cancelled"
        fi
        ;;
    2)
        echo "You are about to SEND changes TO Google Drive"
        read -p "Type 'yes' to confirm: " confirmation
        if [ "$confirmation" = "yes" ]; then
            rclone sync /home/ph/Documents/sync_vault sync-vault:/sync_vault --progress --stats-one-line -v --create-empty-src-dirs
        else
            echo "Operation cancelled"
        fi
        ;;
    *)
        echo "Invalid choice. Please select 1 or 2."
        ;;
esac
